language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly
  - hhvm
#  - hhvm-nightly - not supported now

sudo: false

# Disabled via unexpected fail on TravisCI
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - composer self-update --quiet
  - COMPOSER_DISCARD_CHANGES=true composer --prefer-source update --no-interaction --no-progress

script:
  - make ci

after_script:
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
